name: Example workflow for Node using Snyk
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '00 14 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
        - name: Snyk Test
          uses: snyk/actions/setup@master
        - run: snyk test --sarif-file-output=snyk-sarif.json
          continue-on-error: true       
          env:
            SNYK_TOKEN: ${{ SNYK_TOKEN }}    
