name: Example workflow for Node using Snyk
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '00 14 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: snyk auth
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}   
      - name: Snyk Test
        uses: snyk/actions/setup@master
      - run: snyk test --sarif-file-output=snyk-sarif.json
        continue-on-error: true       
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
         sarif_file: snyk-sarif.json
